services:
  acmpc_gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: acmpc_gazebo
    
    restart: unless-stopped
    
    network_mode: host
    
    ports:
      - "9090:9090"    # rosbridge WebSocket (для Python на хосте)
      - "9002:9002"    # Gazebo WebSocket (для app.gazebosim.org)
    
    environment:
      - ROS_DOMAIN_ID=42
      - TURTLEBOT3_MODEL=burger
      - WORLD_NAME=turtlebot3_empty
    
    volumes:
      - ../configs/worlds:/workspace/worlds:ro
    
    entrypoint: /entrypoint.sh
