services:
  acmpc_gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: acmpc_gazebo
    
    restart: unless-stopped
    
    network_mode: host
    
    # If you want to use network_mode: bridge, you should include ports
    # ports:
    #   - "9090:9090"    # rosbridge WebSocket
    #   - "11345:11345"  # Gazebo Master
    
    environment:
      - ROS_DOMAIN_ID=42
      - TURTLEBOT3_MODEL=burger
      - WORLD_NAME=turtlebot3_dqn_stage2
    
    volumes:
      - ../configs/worlds:/workspace/worlds:ro
      - ../configs/launch:/workspace/launch:ro
    
    entrypoint: /entrypoint.sh
